import { ArrowRight, Compass, Heart, Leaf, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { PageShell } from '@/components/toolora-shell';

export default function About() {
  return (
    <PageShell>
      <main>
        <section className="mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-8 sm:pt-24"><div className="max-w-4xl"><span className="font-mono-ui text-[10px] uppercase tracking-[0.16em] text-primary">A little context</span><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[0.94] tracking-[-0.055em] sm:text-7xl">The internet has enough <span className="text-primary">friction.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Toolora is a small, independent collection of practical tools for the small tasks that interrupt a good flow.</p></div><div className="mt-16 grid gap-4 border-t border-border pt-8 sm:grid-cols-3"><div><p className="font-mono-ui text-3xl text-primary">01</p><h2 className="mt-4 font-display text-2xl">Open</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">No account wall between you and a useful answer.</p></div><div><p className="font-mono-ui text-3xl text-primary">02</p><h2 className="mt-4 font-display text-2xl">Obvious</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">One job per tool. Plain language. No puzzle-box interfaces.</p></div><div><p className="font-mono-ui text-3xl text-primary">03</p><h2 className="mt-4 font-display text-2xl">Respectful</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">When work happens on your device, we’ll tell you plainly.</p></div></div></section>
        <section className="bg-[hsl(37_80%_74%_/_0.45)]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:py-24"><div><span className="font-mono-ui text-[10px] uppercase tracking-[0.16em] text-foreground/60">The shelf note</span><h2 className="mt-4 max-w-sm font-display text-4xl leading-tight tracking-[-0.04em]">Good tools disappear into your day.</h2></div><div className="grid gap-3 sm:grid-cols-2">{[{ icon: Compass, title: 'Made for real use', copy: 'From a student polishing an essay to a developer checking a payload, practical beats impressive.' }, { icon: Leaf, title: 'Light on purpose', copy: 'The browser is plenty powerful. We keep the experience quick, focused, and easy to leave.' }, { icon: ShieldCheck, title: 'Private where it matters', copy: 'Local processing is a feature, not a footnote. We mark it every time.' }, { icon: Heart, title: 'A work in progress', copy: 'Toolora grows by listening for the next tiny task worth making easier.' }].map(({ icon: Icon, title, copy }) => <div key={title} className="rounded-2xl border border-foreground/10 bg-background/40 p-5"><Icon className="h-5 w-5 text-primary" /><h3 className="mt-8 text-sm font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-20 text-center sm:px-8"><p className="font-display text-3xl tracking-[-0.03em]">Ready to get one small thing done?</p><Link href="/tools" data-testid="link-about-tools" className="mt-6 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Open the shelf <ArrowRight className="h-4 w-4" /></Link></section>
      </main>
    </PageShell>
  );
}